#!/bin/bash

service nginx stop
/sbin/iptables -A INPUT -p tcp --dport 80 -j ACCEPT
/usr/bin/certbot renew
/sbin/iptables -D INPUT -p tcp --dport 80 -j ACCEPT
/usr/sbin/postfix reload
service nginx start
